### Create new user
POST http://localhost:3000/api/users
Accept: application/json
Content-Type: application/json

{
  "username": "test",
  "email": "test@gmail.com",
  "firstname": "test",
  "lastname": "test",
  "password": "testtt"
}